Dev
BJTU-SEPractice2023-III/HomeworkPlatformFrontend pull request #4
Opened 2023-10-14 14:36 UTC by tjw2003

2023-10-14 15:08 UTC, AzurIce requested changes
好多要改的。

2023-10-14 15:08 UTC, AzurIce commented on src/index.tsx
> +        {/* 具体课程页面，根据传入的 id 获取课程数据渲染 */}
这个注释如写，一看就是懒B复制

2023-10-14 15:08 UTC, AzurIce commented on src/index.tsx
> +        <Route path="/create" component={Create} />
课程的创建为什么放在 `/create` 而不是 `/course/create`？

2023-10-14 15:08 UTC, AzurIce commented on src/lib/course.ts
> +import {get,post} from "./axios"
格式化下代码，vscode alt shift f说了多少次了（

2023-10-14 15:08 UTC, AzurIce commented on src/lib/course.ts
> +export function create(name: string, description: string, beginDate: string, endDate: string) {
这个地方，可能参数用 datetime 类型好一点（然后界面可能要找一个可以选择的那种日期控件，或者干脆几个框年月日然后用这几个值创建一个datetime值），然后转为符合数据库要求的字符串

2023-10-14 15:08 UTC, AzurIce commented on src/pages/main/Courses.tsx
> +                <TableCell>
这是啥，无关的东西不要add进去一块交，而且这除了画了个界面也没实现任何东西，要不然就分开commit各自写清楚都干了啥

2023-10-14 15:08 UTC, AzurIce commented on src/pages/main/Create.tsx
> +      console.log("[Login]: onLogin")
nmd懒B复制改都不改的？这就直接commit了？

2023-10-14 15:08 UTC, AzurIce commented on src/pages/main/Create.tsx
> +                <span style="color : gray">创建课程需要输入课程名字,开始日期,结束日期,课程简介</span>
格式化下代码，谢谢你

2023-10-14 15:08 UTC, AzurIce commented on src/pages/main/Create.tsx
> +              <div style="font-style: italic; color: gray;">以下空行为必填内容</div>
那我不还是可以不填么，不填我点按钮不还是发过去了么；

2023-10-14 15:08 UTC, AzurIce commented on src/pages/main/Create.tsx
> +              <div style="font-style: italic; color: gray;">以下空行为必填内容</div>
textfield 有一个required类似的参数详见注册页
就像上面说的问题，还要加个验证输没输以及输的信息是否合法才发请求的逻辑。

2023-10-14 15:08 UTC, AzurIce commented on src/pages/main/Main.tsx
> +  async function getlearningcourse() {
为什么改成 async？

2023-10-16 01:49 UTC, AzurIce commented
速速写！

2023-10-17 11:04 UTC, tjw2003 commented on src/index.tsx
> +        {/* 具体课程页面，根据传入的 id 获取课程数据渲染 */}
以改

2023-10-17 11:04 UTC, tjw2003 commented on src/index.tsx
> +        <Route path="/create" component={Create} />
已改

2023-10-17 11:05 UTC, tjw2003 commented on src/lib/course.ts
> +import {get,post} from "./axios"
以格式化

2023-10-17 11:11 UTC, tjw2003 commented on src/pages/main/Courses.tsx
> +                <TableCell>
<TableCell>
                  <Button onClick={() => { }}>选课</Button>
</TableCell>
你一定是说这一段，这一段本来我计划作用选课用的，要不然你要课程界面界面干啥？一是查看课程详情，其次是选课

2023-10-17 11:12 UTC, tjw2003 commented on src/pages/main/Create.tsx
> +      console.log("[Login]: onLogin")
啊，这，反正只是打印东西，无伤大雅。已改

2023-10-17 11:13 UTC, tjw2003 commented on src/pages/main/Create.tsx
> +                <span style="color : gray">创建课程需要输入课程名字,开始日期,结束日期,课程简介</span>
以格式化，不用谢

2023-10-17 13:04 UTC, tjw2003 commented on src/pages/main/Create.tsx
> +              <div style="font-style: italic; color: gray;">以下空行为必填内容</div>
这个我简单写了个判断，但是显然不够

2023-10-17 16:59 UTC, AzurIce commented on src/pages/main/Create.tsx
> +import { useState } from 'react';
大哥了，这怎么用上react了，这都不是一个框架，mui是react框架的东西

2023-10-17 17:01 UTC, AzurIce requested changes
实在绷不住了，我明天写写吧

2023-10-17 17:01 UTC, AzurIce commented on src/pages/main/Create.tsx
> +import { DatePicker } from '@mui/lab';
大哥了，这怎么用上react了，这都不是一个框架，mui是react框架的东

2023-10-17 17:01 UTC, AzurIce commented on src/pages/main/Create.tsx
> +  const [beginDate, setBeginDate] = useState(null);
这页我明天写写吧，实在绷不住了

2023-10-19 05:04 UTC, AzurIce approved these changes

2023-10-19 05:04 UTC, AzurIce approved these changes
我写得真好

2023-10-19 05:04 UTC, merged