Dev
BJTU-SEPractice2023-III/HomeworkPlatformFrontend pull request #6
Opened 2023-11-04 06:45 UTC by tjw2003

blabla

2023-11-04 08:38 UTC, AzurIce commented
艹

2023-11-04 08:39 UTC, tjw2003 commented
关于作业界面，我认为作业界面与课程界面原理上一样，都是homework/1和course/1

2023-11-04 12:14 UTC, AzurIce commented
> 关于作业界面，我认为作业界面与课程界面原理上一样，都是homework/1和course/1

确实

2023-11-06 06:41 UTC, AzurIce commented
你妈的，本地没测好，自己都搞不明白有什么东西改了的 commit 就不要 push 上来，或者说就不要 commit

2023-11-07 12:03 UTC, AzurIce requested changes

2023-11-07 12:03 UTC, AzurIce commented on src/pages/main/Course.tsx
> +        <Show when={course() && isTeaching(course())}>
这个按钮还是放到「作业」那个Tab里面好点我觉得

2023-11-07 12:03 UTC, AzurIce commented on src/pages/main/CreateHomework.tsx
> +            start: "2021-01-31T23:00:00.000Z",
这些默认时间改成根据当前时间来 @AzurIce

2023-11-07 12:03 UTC, AzurIce commented on src/pages/main/CreateHomework.tsx
> +    return (
整个界面还要重新设计下 @AzurIce

2023-11-07 12:03 UTC, AzurIce commented on src/pages/main/Homework.tsx
> +  return (
界面到时候还要再重新设计下 @AzurIce

2023-11-07 12:03 UTC, AzurIce commented on src/pages/main/Course.tsx
> +        <Show when={course() && isTeaching(course())}>
@tjw2003

2023-11-13 07:35 UTC, AzurIce commented
fix: #8

2023-11-13 07:36 UTC, merged